const ROLE_COLORS={consolidator:'#f59e0b',transit:'#45b7d1',distributor:'#ef6c8f',terminal:'#9b8cff',coordinator:'#63d4c5',peripheral:'#718096',frontier:'#e2e8f0'};
let cy, graph, byId={};
const money=n=>{n=Number(n)||0;if(n>=1e6)return`${(n/1e6).toFixed(2)} млн KZT`;if(n>=1e3)return`${(n/1e3).toFixed(1)} тыс. KZT`;return`${n.toLocaleString()} KZT`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function get(url){const r=await fetch(url);if(!r.ok)throw Error((await r.json()).detail||r.statusText);return r.json()}
function showTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${name}-view`));}
function buildGraph(data){graph=data;byId=Object.fromEntries(data.nodes.map(n=>[String(n.id),n]));document.getElementById('loading').remove();cy=cytoscape({container:document.getElementById('cy'),elements:{nodes:data.nodes.map(n=>({data:{id:String(n.id),...n},position:{x:n.x,y:n.y}})),edges:data.edges.map((e,i)=>({data:{id:`e${i}`,source:String(e.source),target:String(e.target),...e}}))},layout:{name:'preset',fit:true,padding:35},style:[{selector:'node',style:{'background-color':e=>ROLE_COLORS[e.data('role')]||'#718096','shape':e=>e.data('is_seed')?'diamond':'ellipse','width':e=>12+Number(e.data('priority')||0)*22,'height':e=>12+Number(e.data('priority')||0)*22,'label':'data(id)','font-size':8,'color':'#cbd5e1','text-valign':'bottom','text-margin-y':5,'border-width':e=>e.data('is_seed')?3:1,'border-color':e=>e.data('is_seed')?'#fff':(e.data('role')==='frontier'?'#e2e8f0':'#263746'),'border-style':e=>e.data('role')==='frontier'?'dashed':'solid'}},{selector:'edge',style:{'line-color':'#526579','target-arrow-color':'#91a8bc','target-arrow-shape':'triangle','curve-style':'bezier','width':e=>1+Math.log10(Number(e.data('sum_kzt')||1))*.65,'opacity':.58}},{selector:'.dim',style:{opacity:.12}},{selector:'.focus',style:{opacity:1}},{selector:'.selected',style:{'border-color':'#fff','border-width':4}}]});cy.on('tap','node',e=>selectNode(e.target.id()));}
function selectNode(id){if(!cy)return;const node=cy.getElementById(String(id));if(!node.length)return;cy.elements().removeClass('dim focus selected');const neighborhood=node.closedNeighborhood();cy.elements().not(neighborhood).addClass('dim');neighborhood.addClass('focus');node.addClass('selected');cy.animate({center:{eles:node},zoom:Math.max(cy.zoom(),1.4)},{duration:350});renderNode(String(id));}
async function renderNode(id){const n=await get(`/api/node/${encodeURIComponent(id)}`);const metrics=[['Priority',Number(n.priority_score??n.priority??0).toFixed(3)],['Role score',Number(n.role_score||0).toFixed(3)],['Cluster',n.cluster_id??n.cluster??'—'],['In / out',`${n.in_deg??'—'} / ${n.out_deg??'—'}`],['Received',money(n.in_kzt)],['Sent',money(n.out_kzt)]];document.getElementById('side').innerHTML=`<div class="node-header"><div><h2>${esc(id)}</h2><span class="role">${esc(n.role)}</span></div><button class="copy" onclick="navigator.clipboard.writeText('${esc(id)}')">Copy</button></div><div class="evidence">${esc(n.evidence||'No evidence supplied.')}</div><div class="metrics">${metrics.map(m=>`<div class="metric"><b>${esc(m[1])}</b><span>${esc(m[0])}</span></div>`).join('')}</div>${flowTable('Who pays',n.incoming,'incoming')}${flowTable('Who gets paid',n.outgoing,'outgoing')}`;}
function flowTable(title,rows){return`<h3>${title} (${rows.length})</h3><table class="flow-table"><tbody>${rows.slice(0,30).map(x=>`<tr onclick="selectNode('${esc(x.gid)}')"><td>${esc(x.gid)}</td><td>${esc(x.role)}</td><td>${money(x.sum_kzt)}</td></tr>`).join('')}</tbody></table>`}
function renderLegend(){document.getElementById('legend').innerHTML=Object.entries(ROLE_COLORS).map(([r,c])=>`<span class="legend-item"><i class="dot" style="background:${c}"></i>${r}</span>`).join('')}
function renderTop(rows){document.querySelector('#top-table tbody').innerHTML=rows.map(r=>`<tr data-gid="${esc(r.gid)}"><td>${r.rank}</td><td>${esc(r.gid)}</td><td>${esc(r.role)}</td><td>${Number(r.priority_score).toFixed(3)}</td><td>${esc(r.why)}</td></tr>`).join('');document.querySelectorAll('#top-table tr[data-gid]').forEach(r=>r.onclick=()=>{showTab('graph');selectNode(r.dataset.gid)});}
function renderClusters(rows){document.querySelector('#clusters-table tbody').innerHTML=rows.map(r=>`<tr><td>${r.cluster_id}</td><td>${r.n_nodes}</td><td>${r.n_seed}</td><td>${money(r.sum_kzt_internal)}</td><td>${esc(r.hypothesis)}</td><td><button class="cluster-btn" onclick="highlightCluster('${r.cluster_id}')">Show</button></td></tr>`).join('');}
function highlightCluster(cluster){showTab('graph');cy.elements().removeClass('dim focus selected');const selected=cy.nodes().filter(n=>String(n.data('cluster'))===String(cluster));cy.elements().not(selected).addClass('dim');selected.addClass('focus');cy.animate({fit:{eles:selected,padding:50}},{duration:350});}
async function search(value){const box=document.getElementById('suggestions');if(!value){box.innerHTML='';return}const rows=await get(`/api/search?q=${encodeURIComponent(value)}`);box.innerHTML=rows.map(r=>`<div class="suggestion" data-gid="${esc(r.gid)}"><b>${esc(r.gid)}</b> · ${esc(r.role)} · ${Number(r.priority).toFixed(3)}</div>`).join('');box.querySelectorAll('.suggestion').forEach(x=>x.onclick=()=>{document.getElementById('search').value=x.dataset.gid;box.innerHTML='';showTab('graph');selectNode(x.dataset.gid)});}
async function init(){renderLegend();buildGraph(await get('/api/graph'));renderTop(await get('/api/top'));renderClusters(await get('/api/clusters'));document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>showTab(x.dataset.tab));document.getElementById('search').oninput=e=>search(e.target.value.trim());document.getElementById('reset').onclick=()=>{cy.elements().removeClass('dim focus selected');document.getElementById('side').innerHTML='<div class="empty">Select a node to inspect its flows.</div>';};}
init().catch(e=>document.getElementById('loading').textContent=e.message);
