var ROLE_COLORS={consolidator:'#f59e0b',transit:'#45b7d1',distributor:'#ef6c8f',terminal:'#9b8cff',coordinator:'#63d4c5',peripheral:'#718096',frontier:'#e2e8f0'};
var cy,graph,byId={},reviewBasket=new Set();
function gid(value){return typeof value==='string'?value:String(value)}
function money(n){n=Number(n)||0;if(n>=1e6)return(n/1e6).toFixed(2)+' млн KZT';if(n>=1e3)return(n/1e3).toFixed(1)+' тыс. KZT';return n.toLocaleString()+' KZT'}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
async function get(url){var r=await fetch(url);if(!r.ok)throw Error((await r.json()).detail||r.statusText);return r.json()}
function showTab(name){document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x.dataset.tab===name)});document.querySelectorAll('.view').forEach(function(x){x.classList.toggle('active',x.id===name+'-view')})}
function buildGraph(data){graph=data;byId={};data.nodes.forEach(function(n){n.id=gid(n.id);n.short_label='…'+n.id.slice(-6);byId[n.id]=n});document.getElementById('loading').remove();cy=cytoscape({container:document.getElementById('cy'),elements:{nodes:data.nodes.map(function(n){return{data:n,position:{x:n.x,y:n.y},grabbable:true}}),edges:data.edges.map(function(e,i){return{data:Object.assign({id:'e'+i,source:gid(e.source),target:gid(e.target)},e)}})},layout:{name:'preset',fit:true,padding:35},minZoom:.05,maxZoom:4,userPanningEnabled:true,userZoomingEnabled:true,autoungrabify:false,boxSelectionEnabled:false,textureOnViewport:true,hideEdgesOnViewport:true,motionBlur:false,pixelRatio:1,style:[{selector:'node',style:{'background-color':function(e){return ROLE_COLORS[e.data('role')]||'#718096'},shape:'ellipse',width:function(e){return 14+Number(e.data('priority')||0)*26},height:function(e){return 14+Number(e.data('priority')||0)*26},label:'data(short_label)','font-size':9,color:'#cbd5e1','text-valign':'bottom','text-margin-y':5,'text-opacity':0,'border-width':function(e){return e.data('is_seed')?4:1},'border-color':function(e){return e.data('is_seed')?'#f6c453':e.data('role')==='frontier'?'#e2e8f0':'#263746'},'border-style':function(e){return e.data('role')==='frontier'?'dashed':'solid'}}},{selector:'node.show-label',style:{'text-opacity':1}},{selector:'node.selected',style:{'overlay-color':'#63d4ff','overlay-opacity':.35,'overlay-padding':6,'border-color':'#63d4ff','border-width':4}},{selector:'edge',style:{'line-color':'#526579','target-arrow-color':'#91a8bc','target-arrow-shape':'triangle','curve-style':'straight',width:function(e){return Math.max(1,Math.min(6,Math.log10(Number(e.data('sum_kzt')||1)-1)*.75))},opacity:.58}},{selector:'.dim',style:{opacity:.12}},{selector:'.focus',style:{opacity:1}},{selector:'.incoming',style:{'line-color':'#63d4ff','target-arrow-color':'#63d4ff'}},{selector:'.outgoing',style:{'line-color':'#f6c453','target-arrow-color':'#f6c453'}}]});function labels(){cy.batch(function(){cy.nodes().toggleClass('show-label',cy.zoom()>=1.2);cy.nodes('.selected').closedNeighborhood().nodes().addClass('show-label')})}var timer;cy.on('zoom',function(){clearTimeout(timer);timer=setTimeout(labels,100)});labels();cy.nodes().grabify();cy.on('tap','node',function(e){selectNode(e.target.id())})}
function selectNode(id){var node=cy&&cy.getElementById(gid(id));if(!node||!node.length)return;var neighborhood=node.closedNeighborhood();cy.elements().removeClass('dim focus selected incoming outgoing');cy.elements().not(neighborhood).addClass('dim');neighborhood.addClass('focus show-label');node.addClass('selected');node.incomers('edge').addClass('incoming');node.outgoers('edge').addClass('outgoing');cy.animate({center:{eles:node},zoom:Math.max(cy.zoom(),1.4)},{duration:300});renderNode(gid(id))}
function scoreBars(b){if(!b||typeof b!=='object')return'<div class="muted">—</div>';return Object.keys(b).map(function(k){var v=Number(b[k]);return'<div class="score-row"><span>'+esc(k)+'</span><i><b style="width:'+Math.min(100,Math.max(0,v*100))+'%"></b></i><em>'+v.toFixed(3)+'</em></div>'}).join('')}
function flowTable(title,rows){return'<h3>'+title+' ('+rows.length+')</h3><table class="flow-table"><tbody>'+rows.slice(0,30).map(function(x){return'<tr onclick="selectNode(\''+esc(x.gid)+'\')"><td>'+esc(x.gid)+'</td><td>'+esc(x.role)+'</td><td>'+money(x.sum_kzt)+'</td></tr>'}).join('')+'</tbody></table>'}
async function renderNode(id){var pair=await Promise.all([get('/api/node/'+encodeURIComponent(id)),get('/api/node/'+encodeURIComponent(id)+'/card')]);var n=pair[0],card=pair[1];var metrics=[['Priority',Number(n.priority_score||n.priority||0).toFixed(3)],['Role score',Number(n.role_score||0).toFixed(3)],['Cluster',n.cluster_id||n.cluster||'—'],['In / out',(n.in_deg||'—')+' / '+(n.out_deg||'—')],['Received',money(n.in_kzt)],['Sent',money(n.out_kzt)],['p_terminal',n.p_terminal||'—']];var marked=reviewBasket.has(id);document.getElementById('side').innerHTML='<div class="node-header"><div><h2>'+esc(id)+'</h2><span class="role">'+esc(n.role)+'</span></div><button class="copy" onclick="navigator.clipboard.writeText(\''+esc(id)+'\')">Copy</button></div><div class="evidence">'+esc(n.evidence||'No evidence supplied.')+'</div><button class="review-btn" onclick="toggleReview(\''+esc(id)+'\')">'+(marked?'Remove from review list':'Add to review list')+'</button><h3>Next steps</h3><ul class="next-steps">'+card.next_steps.map(function(x){return'<li>'+esc(x)+'</li>'}).join('')+'</ul><div class="attention">'+esc(card.attention)+'</div><h3>Priority breakdown</h3><div class="score-bars">'+scoreBars(card.score_breakdown)+'</div><div class="metrics">'+metrics.map(function(m){return'<div class="metric"><b>'+esc(m[1])+'</b><span>'+esc(m[0])+(m[0]==='p_terminal'?' · estimate by analogues':'')+'</span></div>'}).join('')+'</div>'+flowTable('Who pays',n.incoming)+flowTable('Who gets paid',n.outgoing)}
function toggleReview(id){if(reviewBasket.has(id))reviewBasket.delete(id);else reviewBasket.add(id);renderNode(id)}
function csvDownload(rows,name){if(!rows.length)return;var keys=Object.keys(rows[0]);var body=[keys.join(',')].concat(rows.map(function(r){return keys.map(function(k){return'"'+String(r[k]==null?'':r[k]).replaceAll('"','""')+'"'}).join(',')})).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function renderLegend(){document.getElementById('legend').innerHTML=Object.keys(ROLE_COLORS).map(function(r){return'<span class="legend-item"><i class="dot" style="background:'+ROLE_COLORS[r]+'"></i>'+r+'</span>'}).join('')}
function renderTop(rows){document.querySelector('#top-table tbody').innerHTML=rows.map(function(r){return'<tr data-gid="'+esc(r.gid)+'"><td>'+r.rank+'</td><td>'+esc(r.gid)+'</td><td>'+esc(r.role)+'</td><td>'+Number(r.priority_score).toFixed(3)+'</td><td>'+esc(r.why)+'</td></tr>'}).join('');document.querySelectorAll('#top-table tr[data-gid]').forEach(function(r){r.onclick=function(){showTab('graph');selectNode(r.dataset.gid)}});document.getElementById('top-export').onclick=function(){csvDownload(rows,'top_nodes.csv')}}
function renderClusters(rows){document.querySelector('#clusters-table tbody').innerHTML=rows.map(function(r){return'<tr><td>'+r.cluster_id+'</td><td>'+r.n_nodes+'</td><td>'+r.n_seed+'</td><td>'+money(r.sum_kzt_internal)+'</td><td>'+esc(r.hypothesis)+'</td><td><button class="cluster-btn" onclick="highlightCluster(\''+r.cluster_id+'\')">Show</button></td></tr>'}).join('')}
function highlightCluster(cluster){showTab('graph');cy.elements().removeClass('dim focus selected');var selected=cy.nodes().filter(function(n){return String(n.data('cluster'))===String(cluster)});cy.elements().not(selected).addClass('dim');selected.addClass('focus');cy.animate({fit:{eles:selected,padding:50}},{duration:350})}
async function search(value){var box=document.getElementById('suggestions');if(!value){box.innerHTML='';return}var query=gid(value);var rows=Object.keys(byId).filter(function(id){return id.indexOf(query)===0||id.endsWith(query)}).slice(0,12).map(function(id){return byId[id]});box.innerHTML=rows.map(function(r){return'<div class="suggestion" data-gid="'+esc(gid(r.id))+'"><b>'+esc(gid(r.id))+'</b> · '+esc(r.role)+' · '+Number(r.priority).toFixed(3)+'</div>'}).join('');box.querySelectorAll('.suggestion').forEach(function(x){x.onclick=function(){document.getElementById('search').value=x.dataset.gid;box.innerHTML='';showTab('graph');selectNode(x.dataset.gid)}})}
async function init(){renderLegend();buildGraph(await get('/api/graph'));renderTop(await get('/api/top'));renderClusters(await get('/api/clusters'));document.querySelectorAll('.tab').forEach(function(x){x.onclick=function(){showTab(x.dataset.tab)}});document.getElementById('search').oninput=function(e){search(e.target.value.trim())};document.getElementById('reset').onclick=function(){cy.elements().removeClass('dim focus selected');document.getElementById('side').innerHTML='<div class="empty">Select a node to inspect its flows.</div>'};document.getElementById('basket-export').onclick=function(){csvDownload(Array.from(reviewBasket).map(function(id){return byId[id]||{id:id}}),'review_list.csv')}}
init().catch(function(e){document.getElementById('loading').textContent=e.message});
