var clusterColors=['#63d4c5','#f59e0b','#ef6c8f','#9b8cff','#45b7d1','#e2e8f0'];
function addGraphTools(){
  var host=document.getElementById('graph-view');if(!host||document.getElementById('graph-tools'))return;
  var box=document.createElement('div');box.id='graph-tools';box.innerHTML='<input id="ego-gid" placeholder="Ego GID"><select id="ego-k"><option>1</option><option>2</option><option>3</option></select><select id="ego-direction"><option value="both">both</option><option value="up">up</option><option value="down">down</option></select><button id="ego-apply">Ego network</button><input id="min-edge" type="range" min="0" max="1000000" step="5000" value="0"><span id="min-edge-label">Min edge: 0</span><button id="color-mode">Color: role</button><div><input id="path-src" placeholder="Path source"><input id="path-dst" placeholder="Path destination"><button id="path-apply">Show path</button><button id="network-reset">Whole network</button></div>';
  host.appendChild(box);
  document.getElementById('ego-apply').onclick=async function(){var gid=document.getElementById('ego-gid').value.trim();if(!gid)return;var data=await get('/api/node/'+encodeURIComponent(gid)+'/ego?k='+document.getElementById('ego-k').value+'&direction='+document.getElementById('ego-direction').value);var ids=new Set(data.nodes.map(function(n){return String(n.id||n.gid)}));cy.elements().removeClass('dim focus selected');cy.nodes().filter(function(n){return !ids.has(String(n.id()))}).addClass('dim');cy.nodes().filter(function(n){return ids.has(String(n.id()))}).addClass('focus')};
  document.getElementById('network-reset').onclick=function(){cy.elements().removeClass('dim focus selected')};
  document.getElementById('path-apply').onclick=async function(){var src=document.getElementById('path-src').value.trim(),dst=document.getElementById('path-dst').value.trim();if(!src||!dst)return;var data=await get('/api/path?src='+encodeURIComponent(src)+'&dst='+encodeURIComponent(dst));cy.elements().removeClass('dim focus selected');var ids=new Set(data.gids);cy.nodes().filter(function(n){return !ids.has(String(n.id()))}).addClass('dim');data.gids.forEach(function(id){cy.getElementById(id).addClass('focus')});data.edges.forEach(function(e){cy.edges().filter(function(x){return x.data('source')===e.source&&x.data('target')===e.target}).addClass('selected')})};
  document.getElementById('min-edge').oninput=function(e){var amount=Number(e.target.value);document.getElementById('min-edge-label').textContent='Min edge: '+amount.toLocaleString();cy.edges().forEach(function(edge){edge.toggleClass('dim',Number(edge.data('sum_kzt')||0)<amount)})};
  document.getElementById('color-mode').onclick=function(){var cluster=this.textContent.indexOf('role')>=0;this.textContent='Color: '+(cluster?'cluster':'role');cy.nodes().forEach(function(n){n.style('background-color',cluster?clusterColors[Number(n.data('cluster')||0)%clusterColors.length]:(ROLE_COLORS[n.data('role')]||'#718096'))})};
}
setTimeout(addGraphTools,700);
